#apiVersion: networking.k8s.io/v1beta1
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mopidy
  namespace: music
  annotations:
    #    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/app-root: /muse/
    # add an annotation indicating the issuer to use.
    cert-manager.io/issuer: selfsigned-crt
spec:
  rules:
  - host: mopidy.home
    http:
      paths:
      - path: /
        backend:
          serviceName: mopidy
          servicePort: http
  tls:
  - hosts:
    - mopidy.home
    secretName: tls-secret
