version: "3.9"

services:
  deploy-mopidy:
    image: bitnami/kubectl
    command: apply -f /manifests/
    volumes:
      - ./mopidy:/manifests/
      - ../creds/kube/:/.kube/

  undeploy-mopidy:
    image: bitnami/kubectl
    command: delete -f /manifests/
    volumes:
      - ./mopidy:/manifests/
      - ../creds/kube/:/.kube/

  deploy-snap:
    image: bitnami/kubectl
    command: apply -f /manifests/
    volumes:
      - ./snapserver:/manifests/
      - ../creds/kube/:/.kube/

  undeploy-snap:
    image: bitnami/kubectl
    command: delete -f /manifests/
    volumes:
      - ./snapserver:/manifests/
      - ../creds/kube/:/.kube/

  deploy-fast:
    image: bitnami/kubectl
    command: apply -f /manifests/
    volumes:
      - ./fast:/manifests/
      - ../creds/kube/:/.kube/

  undeploy-fast:
    image: bitnami/kubectl
    command: delete -f /manifests/
    volumes:
      - ./fast:/manifests/
      - ../creds/kube/:/.kube/

  pods:
    image: bitnami/kubectl
    command: get pods -n music
    volumes:
      - ../creds/kube/:/.kube/
