version: "3.9"

services:
  kubectl:
    image: bitnami/kubectl
    working_dir: /manifests
    volumes:
      - ../creds/kube/:/.kube/:ro
      - .:/manifests

  kustomize:
    image: traherom/kustomize-docker
    command: kubectl get pods --all-namespaces
    volumes:
      - ../creds/kube/config:/root/.kube/config:ro

