---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: browser-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.40
    path: /media/music/music
  storageClassName: ""