apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pvc
  namespace: fast
  labels:
    app: fast
    component: fast
    tier: storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: fast
  labels:
    app: db
    component: fast
    tier: storage
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi

      