---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch
  namespace: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch
  template:
    metadata:
      labels:
        app: scratch
    spec:
      containers:
      - name: scratch
        image: docker-registry.home/scratch:test
        command: ["webpack" ]
        args: ["serve", "--host", "0.0.0.0"]
        ports:
        - containerPort: 8080
          protocol: TCP 
        envFrom:
        - configMapRef:
            name: scratch-config
#        livenessProbe:
#          httpGet:
#            scheme: HTTP
#            path: /
#            port: 80
#          initialDelaySeconds: 60
#          timeoutSeconds: 30
#        readinessProbe:
#          httpGet:
#            path: /
#            scheme: HTTP
#            port: 80
#          initialDelaySeconds: 20
#          timeoutSeconds: 30
#        resources:
#          limits:
#            cpu: "500m"
#            memory: "400Mi"
#          requests:
#            cpu: "100m"
#            memory: "100Mi"
        imagePullPolicy: Always
