apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fast
  namespace: fast
spec:
  rules:
  - host: scratch.home
    http:
      paths:
      - path: /
        backend:
          serviceName: scratch-service
          servicePort: http-scratch
      - path: /api
        backend:
          serviceName: fast
          servicePort: http
      - path: /docs
        backend:
          serviceName: fast
          servicePort: http
      - path: /openapi.json
        backend:
          serviceName: fast
          servicePort: http
  - host: pgadmin.home
    http:
      paths:
      - path: /
        backend:
          serviceName: pgadmin-service
          servicePort: pgadmin-http
  tls:
  - hosts:
    - scratch.home
    - pgadmin.home
    secretName: tls-secret
